# Generated by Django 5.0.7 on 2024-08-06 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0002_meeting_alter_course_course_credits"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Topic", models.CharField(max_length=200)),
                ("Langauges", models.CharField(max_length=200)),
                ("Duration", models.IntegerField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_app.student",
                    ),
                ),
            ],
        ),
    ]
